import { Injectable, NotFoundException } from '@nestjs/common';
import { randomUUID } from 'node:crypto';
import { DatabaseService } from '../database/database.service';
import { assessRequest, riskLevel } from '../common/risk';
import type { SessionUser } from '../common/types';

const now = () => new Date().toISOString();
const isoDay = (days=0) => new Date(Date.now()+days*86400000).toISOString().slice(0,10);

@Injectable()
export class StoreService {
  private users: SessionUser[] = [{ id:'usr-demo', email:'admin@psuwit.ac.th', name:'ผู้ดูแลระบบสาธิต', department:'ฝ่ายเทคโนโลยีสารสนเทศ', roles:['DIRECTOR'] }];
  private requests: any[] = [
    { id:'req-1', requestNo:'DG-2569-0001', type:'การใช้เครื่องมือ AI', title:'การใช้ AI ช่วยจัดทำสื่อการเรียนรู้', objective:'เพิ่มประสิทธิภาพการจัดทำสื่อโดยมีครูตรวจสอบผลลัพธ์', description:'ใช้เฉพาะข้อมูลที่ไม่ระบุตัวบุคคล', department:'กลุ่มสาระวิทยาศาสตร์', ownerName:'นางสาวตัวอย่าง ครูผู้สอน', dataClassification:'INTERNAL', status:'REVIEWING', riskLevel:'MEDIUM', riskScore:8, createdAt:isoDay(-7), updatedAt:now(), dueDate:isoDay(5) },
    { id:'req-2', requestNo:'DG-2569-0002', type:'การเชื่อมต่อ API/ฐานข้อมูล', title:'เชื่อมต่อระบบทะเบียนกิจกรรม', objective:'ลดการบันทึกข้อมูลซ้ำ', description:'เชื่อมต่อด้วยบัญชีบริการแบบสิทธิ์ต่ำสุด', department:'ฝ่ายกิจการนักเรียน', ownerName:'นายตัวอย่าง เจ้าหน้าที่', dataClassification:'CONFIDENTIAL', status:'PENDING_APPROVAL', riskLevel:'HIGH', riskScore:12, createdAt:isoDay(-4), updatedAt:now(), dueDate:isoDay(2) },
    { id:'req-3', requestNo:'DG-2569-0003', type:'การใช้ Cloud/Hosting', title:'เว็บไซต์ประชาสัมพันธ์โครงการ', objective:'เผยแพร่ข่าวสารสาธารณะ', description:'ไม่มีข้อมูลส่วนบุคคล', department:'ฝ่ายประชาสัมพันธ์', ownerName:'นางสาวประชาสัมพันธ์', dataClassification:'PUBLIC', status:'APPROVED', riskLevel:'LOW', riskScore:2, createdAt:isoDay(-12), updatedAt:isoDay(-2) },
  ];
  private timelines: any[] = [{id:'tl-1',requestId:'req-1',action:'SUBMITTED',note:'ส่งคำขอเพื่อพิจารณา',actorName:'นางสาวตัวอย่าง ครูผู้สอน',createdAt:isoDay(-7)}];
  private approvals: any[] = [];
  private registers: any[] = [{id:'reg-1',category:'AI_TOOL',code:'AI-001',name:'เครื่องมือสร้างสื่อการเรียนรู้',ownerName:'หัวหน้ากลุ่มสาระวิทยาศาสตร์',department:'กลุ่มสาระวิทยาศาสตร์',classification:'INTERNAL',status:'ACTIVE',reviewDate:isoDay(120),details:{purpose:'จัดทำสื่อ'}}];
  private risks: any[] = [{id:'risk-1',code:'RSK-001',title:'บัญชีผู้ดูแลไม่มีการยืนยันตัวตนหลายปัจจัย',category:'CYBER',likelihood:3,impact:5,score:15,level:'HIGH',controls:'บังคับใช้ MFA และทบทวนสิทธิ์ทุกภาคเรียน',ownerName:'ผู้ดูแลระบบ',residualScore:6,status:'IN_PROGRESS',dueDate:isoDay(14)}];
  private incidents: any[] = [{id:'inc-1',incidentNo:'INC-2569-0001',title:'ตรวจพบการเข้าสู่ระบบผิดปกติ',category:'ACCOUNT',severity:'MEDIUM',status:'IN_PROGRESS',reporterName:'ผู้ดูแลระบบ',occurredAt:new Date(Date.now()-86400000).toISOString(),description:'พบความพยายามเข้าสู่ระบบหลายครั้งจากอุปกรณ์ใหม่',responseAction:'ระงับเซสชันและให้ผู้ใช้เปลี่ยนรหัสผ่าน',createdAt:now()}];
  private evidence: any[] = [];
  private audits: any[] = [];
  private settings: Record<string, any> = { schoolName:'โรงเรียน มอ.วิทยานุสรณ์', allowedDomain:'psuwit.ac.th', driveFolderId:'', incidentEmail:'security@psuwit.ac.th', reviewReminderDays:30 };
  constructor(private readonly db: DatabaseService) {}
  private demo() { return !this.db.enabled(); }
  private async audit(user: SessionUser, action:string, entityType:string, entityId:string, detail:unknown={}) { const row={id:randomUUID(),userId:user.id,actorName:user.name,action,entityType,entityId,detail,createdAt:now()}; if(this.demo()) this.audits.unshift(row); else await this.db.execute('INSERT INTO audit_logs (id,user_id,actor_name,action,entity_type,entity_id,detail_json,created_at) VALUES (?,?,?,?,?,?,?,NOW())',[row.id,user.id,user.name,action,entityType,entityId,JSON.stringify(detail)]); }
  async getDemoAdmin(){ return this.users[0]; }
  async upsertUser(input: Omit<SessionUser,'id'>) {
    if(this.demo()){let user=this.users.find(u=>u.email===input.email);if(!user){user={...input,id:randomUUID()};this.users.push(user);}return user;}
    const existing=await this.db.query<any>('SELECT id,email,name,department FROM users WHERE email=?',[input.email]);
    let id=existing[0]?.id;
    if(!id){id=randomUUID();await this.db.execute('INSERT INTO users (id,email,name,department,status,created_at,updated_at) VALUES (?,?,?,?,\'ACTIVE\',NOW(),NOW())',[id,input.email,input.name,input.department]);const initialAdmin=process.env.INITIAL_ADMIN_EMAIL?.toLowerCase()===input.email.toLowerCase();await this.db.execute('INSERT INTO user_roles (user_id,role_code) VALUES (?,?)',[id,initialAdmin?'DIRECTOR':'USER']);}
    return this.getUser(id);
  }
  async getUser(id:string):Promise<SessionUser>{if(this.demo()){const u=this.users.find(x=>x.id===id);if(!u)throw new NotFoundException('ไม่พบผู้ใช้');return u;}const rows=await this.db.query<any>('SELECT id,email,name,department FROM users WHERE id=?',[id]);if(!rows[0])throw new NotFoundException('ไม่พบผู้ใช้');const roles=await this.db.query<any>('SELECT role_code FROM user_roles WHERE user_id=?',[id]);return {...rows[0],roles:roles.map(r=>r.roleCode)};}
  async listUsers(){if(this.demo())return this.users;const rows=await this.db.query<any>('SELECT id FROM users WHERE status=\'ACTIVE\' ORDER BY name');return Promise.all(rows.map(r=>this.getUser(r.id)));}
  async setRoles(id:string,roles:string[],actor:SessionUser){if(this.demo()){const u=await this.getUser(id);u.roles=roles;await this.audit(actor,'UPDATE_ROLES','USER',id,{roles});return u;}await this.db.execute('DELETE FROM user_roles WHERE user_id=?',[id]);for(const role of roles)await this.db.execute('INSERT INTO user_roles (user_id,role_code) VALUES (?,?)',[id,role]);await this.audit(actor,'UPDATE_ROLES','USER',id,{roles});return this.getUser(id);}
  async listRequests(){if(this.demo())return [...this.requests].sort((a,b)=>String(b.updatedAt).localeCompare(String(a.updatedAt)));return this.db.query<any>('SELECT id,request_no,type,title,objective,description,department,owner_name,data_classification,status,risk_level,risk_score,created_at,updated_at,due_date FROM requests ORDER BY updated_at DESC');}
  async getRequest(id:string){let item:any;if(this.demo())item=this.requests.find(r=>r.id===id);else item=(await this.db.query<any>('SELECT id,request_no,type,title,objective,description,department,owner_name,data_classification,status,risk_level,risk_score,created_at,updated_at,due_date FROM requests WHERE id=?',[id]))[0];if(!item)throw new NotFoundException('ไม่พบคำขอ');const timeline=this.demo()?this.timelines.filter(t=>t.requestId===id):await this.db.query<any>('SELECT id,action,note,actor_name,created_at FROM request_timeline WHERE request_id=? ORDER BY created_at DESC',[id]);const approvals=this.demo()?this.approvals.filter(a=>a.requestId===id):await this.db.query<any>('SELECT id,decision,comment,approver_name,created_at FROM approvals WHERE request_id=? ORDER BY created_at DESC',[id]);return {...item,timeline,approvals};}
  async createRequest(body:any,user:SessionUser){const id=randomUUID(),assessment=assessRequest(body),count=(await this.listRequests()).length+1,requestNo=`DG-${new Date().getFullYear()+543}-${String(count).padStart(4,'0')}`;const item={id,requestNo,type:body.type,title:body.title,objective:body.objective,description:body.description||'',department:body.department||user.department,ownerName:user.name,dataClassification:body.dataClassification||'INTERNAL',status:'SUBMITTED',riskLevel:assessment.level,riskScore:assessment.score,createdAt:now(),updatedAt:now(),dueDate:body.requestedGoLiveDate||null};if(this.demo())this.requests.unshift(item);else await this.db.execute('INSERT INTO requests (id,request_no,type,title,objective,description,department,owner_id,owner_name,data_classification,status,risk_level,risk_score,due_date,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[id,requestNo,item.type,item.title,item.objective,item.description,item.department,user.id,user.name,item.dataClassification,item.status,item.riskLevel,item.riskScore,item.dueDate]);await this.addTimeline(id,{action:'SUBMITTED',note:'บันทึกและส่งคำขอเข้าสู่กระบวนการพิจารณา'},user);await this.audit(user,'CREATE','REQUEST',id,{requestNo});return this.getRequest(id);}
  async addTimeline(requestId:string,body:any,user:SessionUser){await this.getRequest(requestId);const row={id:randomUUID(),requestId,action:body.action||'COMMENT',note:body.note||'',actorName:user.name,createdAt:now()};if(this.demo())this.timelines.unshift(row);else await this.db.execute('INSERT INTO request_timeline (id,request_id,action,note,actor_id,actor_name,created_at) VALUES (?,?,?,?,?,?,NOW())',[row.id,requestId,row.action,row.note,user.id,user.name]);await this.audit(user,row.action,'REQUEST',requestId,{note:row.note});return row;}
  async decideRequest(id:string,body:any,user:SessionUser){await this.getRequest(id);const allowed=['APPROVED','APPROVED_WITH_CONDITIONS','NEED_INFO','REJECTED','PENDING_APPROVAL','REVIEWING'];const decision=allowed.includes(body.decision)?body.decision:'REVIEWING';const approval={id:randomUUID(),requestId:id,decision,comment:body.comment||'',approverName:user.name,createdAt:now()};if(this.demo()){this.approvals.unshift(approval);const req=this.requests.find(r=>r.id===id);req.status=decision;req.conditions=body.comment||'';req.updatedAt=now();}else{await this.db.execute('INSERT INTO approvals (id,request_id,decision,comment,approver_id,approver_name,created_at) VALUES (?,?,?,?,?,?,NOW())',[approval.id,id,decision,approval.comment,user.id,user.name]);await this.db.execute('UPDATE requests SET status=?,conditions=?,updated_at=NOW() WHERE id=?',[decision,approval.comment,id]);}await this.addTimeline(id,{action:decision,note:approval.comment},user);return this.getRequest(id);}
  async listRegisters(category?:string){if(this.demo())return this.registers.filter(r=>!category||r.category===category);return this.db.query<any>(`SELECT id,category,code,name,owner_name,department,classification,status,review_date,details_json AS details FROM registers ${category?'WHERE category=?':''} ORDER BY code`,category?[category]:[]);}
  async createRegister(body:any,user:SessionUser){const count=(await this.listRegisters(body.category)).length+1,prefix=({AI_TOOL:'AI',SYSTEM:'SYS',DATASET:'DATA',VENDOR:'VEN',INTEGRATION:'API',ADMIN_ACCOUNT:'ADM'} as any)[body.category]||'REG';const row={id:randomUUID(),category:body.category,code:`${prefix}-${String(count).padStart(3,'0')}`,name:body.name,ownerName:body.ownerName,department:body.department,classification:body.classification||'INTERNAL',status:'ACTIVE',reviewDate:body.reviewDate||null,details:body.details||{}};if(this.demo())this.registers.push(row);else await this.db.execute('INSERT INTO registers (id,category,code,name,owner_name,department,classification,status,review_date,details_json,created_at,updated_at) VALUES (?,?,?,?,?,?,?,\'ACTIVE\',?,?,NOW(),NOW())',[row.id,row.category,row.code,row.name,row.ownerName,row.department,row.classification,row.reviewDate,JSON.stringify(row.details)]);await this.audit(user,'CREATE','REGISTER',row.id,{code:row.code});return row;}
  async updateRegister(id:string,body:any,user:SessionUser){if(this.demo()){const row=this.registers.find(r=>r.id===id);if(!row)throw new NotFoundException('ไม่พบทะเบียน');Object.assign(row,{status:body.status??row.status,reviewDate:body.reviewDate??row.reviewDate});await this.audit(user,'UPDATE','REGISTER',id,body);return row;}await this.db.execute('UPDATE registers SET status=COALESCE(?,status),review_date=COALESCE(?,review_date),updated_at=NOW() WHERE id=?',[body.status||null,body.reviewDate||null,id]);await this.audit(user,'UPDATE','REGISTER',id,body);return (await this.db.query<any>('SELECT id,category,code,name,owner_name,department,classification,status,review_date FROM registers WHERE id=?',[id]))[0];}
  async listRisks(){if(this.demo())return this.risks;return this.db.query<any>('SELECT id,code,title,category,likelihood,impact,score,level,controls,owner_name,residual_score,status,due_date FROM risks ORDER BY score DESC');}
  async createRisk(body:any,user:SessionUser){const score=Number(body.likelihood)*Number(body.impact),count=(await this.listRisks()).length+1;const row={id:randomUUID(),code:`RSK-${String(count).padStart(3,'0')}`,title:body.title,category:body.category,likelihood:Number(body.likelihood),impact:Number(body.impact),score,level:riskLevel(score),controls:body.controls,ownerName:body.ownerName,residualScore:score,status:'OPEN',dueDate:body.dueDate||null};if(this.demo())this.risks.unshift(row);else await this.db.execute('INSERT INTO risks (id,code,title,category,likelihood,impact,score,level,controls,owner_name,residual_score,status,due_date,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,NOW(),NOW())',[row.id,row.code,row.title,row.category,row.likelihood,row.impact,row.score,row.level,row.controls,row.ownerName,row.residualScore,row.status,row.dueDate]);await this.audit(user,'CREATE','RISK',row.id,{code:row.code});return row;}
  async updateRisk(id:string,body:any,user:SessionUser){if(this.demo()){const row=this.risks.find(r=>r.id===id);if(!row)throw new NotFoundException('ไม่พบความเสี่ยง');Object.assign(row,{status:body.status??row.status,controls:body.controls??row.controls,residualScore:body.residualScore??row.residualScore,dueDate:body.dueDate??row.dueDate});await this.audit(user,'UPDATE','RISK',id,body);return row;}await this.db.execute('UPDATE risks SET status=COALESCE(?,status),controls=COALESCE(?,controls),residual_score=COALESCE(?,residual_score),due_date=COALESCE(?,due_date),updated_at=NOW() WHERE id=?',[body.status||null,body.controls||null,body.residualScore??null,body.dueDate||null,id]);await this.audit(user,'UPDATE','RISK',id,body);return (await this.db.query<any>('SELECT id,code,title,category,likelihood,impact,score,level,controls,owner_name,residual_score,status,due_date FROM risks WHERE id=?',[id]))[0];}
  async listIncidents(){if(this.demo())return this.incidents;return this.db.query<any>('SELECT id,incident_no,title,category,severity,status,reporter_name,occurred_at,description,response_action,created_at FROM incidents ORDER BY occurred_at DESC');}
  async createIncident(body:any,user:SessionUser){const count=(await this.listIncidents()).length+1,row={id:randomUUID(),incidentNo:`INC-${new Date().getFullYear()+543}-${String(count).padStart(4,'0')}`,title:body.title,category:body.category,severity:body.severity,status:'OPEN',reporterName:user.name,occurredAt:body.occurredAt||now(),description:body.description,responseAction:body.responseAction||'',createdAt:now()};if(this.demo())this.incidents.unshift(row);else await this.db.execute('INSERT INTO incidents (id,incident_no,title,category,severity,status,reporter_id,reporter_name,occurred_at,description,response_action,created_at,updated_at) VALUES (?,?,?,?,?,\'OPEN\',?,?,?,?,?,NOW(),NOW())',[row.id,row.incidentNo,row.title,row.category,row.severity,user.id,user.name,row.occurredAt,row.description,row.responseAction]);await this.audit(user,'CREATE','INCIDENT',row.id,{incidentNo:row.incidentNo,severity:row.severity});return row;}
  async updateIncident(id:string,body:any,user:SessionUser){if(this.demo()){const row=this.incidents.find(i=>i.id===id);if(!row)throw new NotFoundException('ไม่พบเหตุการณ์');Object.assign(row,{status:body.status??row.status,responseAction:body.responseAction??row.responseAction});await this.audit(user,'UPDATE','INCIDENT',id,body);return row;}await this.db.execute('UPDATE incidents SET status=COALESCE(?,status),response_action=COALESCE(?,response_action),updated_at=NOW() WHERE id=?',[body.status||null,body.responseAction||null,id]);await this.audit(user,'UPDATE','INCIDENT',id,body);return (await this.db.query<any>('SELECT id,incident_no,title,category,severity,status,reporter_name,occurred_at,description,response_action,created_at FROM incidents WHERE id=?',[id]))[0];}
  async dashboard(){const [requests,risks,incidents,registers]=await Promise.all([this.listRequests(),this.listRisks(),this.listIncidents(),this.listRegisters()]);const statuses=['SUBMITTED','REVIEWING','PENDING_APPROVAL','APPROVED'],openRisks=risks.filter(r=>r.status!=='CLOSED'),openIncidents=incidents.filter(i=>!['RESOLVED','CLOSED'].includes(i.status));return{metrics:{openRequests:requests.filter(r=>!['APPROVED','REJECTED','CLOSED'].includes(r.status)).length,pendingApprovals:requests.filter(r=>r.status==='PENDING_APPROVAL').length,highRisks:openRisks.filter(r=>['HIGH','CRITICAL'].includes(r.level)).length,openIncidents:openIncidents.length,overdueReviews:registers.filter(r=>r.reviewDate&&r.reviewDate<isoDay()).length,complianceRate:Math.max(0,Math.round(100-(openRisks.filter(r=>['HIGH','CRITICAL'].includes(r.level)).length*8)-(openIncidents.length*3)))},requestsByStatus:statuses.map(label=>({label,value:requests.filter(r=>r.status===label).length})),recentRequests:requests.slice(0,5),urgentItems:[...openRisks.filter(r=>['HIGH','CRITICAL'].includes(r.level)).map(r=>({id:r.id,type:'ความเสี่ยง',title:r.title,level:r.level,dueDate:r.dueDate})),...openIncidents.filter(i=>['HIGH','CRITICAL'].includes(i.severity)).map(i=>({id:i.id,type:'เหตุการณ์',title:i.title,level:i.severity}))].slice(0,5)};}
  async getSettings(){if(this.demo())return this.settings;const rows=await this.db.query<any>('SELECT key_name,value_text FROM settings');const base={...this.settings};for(const r of rows)(base as any)[r.keyName]=r.keyName==='reviewReminderDays'?Number(r.valueText):r.valueText;return base;}
  async saveSettings(body:any,user:SessionUser){for(const [key,value] of Object.entries(body)){if(this.demo())this.settings[key]=value;else await this.db.execute('INSERT INTO settings (key_name,value_text,updated_at) VALUES (?,?,NOW()) ON DUPLICATE KEY UPDATE value_text=VALUES(value_text),updated_at=NOW()',[key,String(value)]);}await this.audit(user,'UPDATE','SETTINGS','global',{});return this.getSettings();}
  async addEvidence(body:any,user:SessionUser){const row={id:randomUUID(),entityType:body.entityType,entityId:body.entityId,fileName:body.fileName,mimeType:body.mimeType,sizeBytes:Number(body.sizeBytes||0),driveFileId:body.driveFileId,driveWebUrl:body.driveWebUrl||'',uploadedBy:user.name,createdAt:now()};if(this.demo())this.evidence.push(row);else await this.db.execute('INSERT INTO evidence_files (id,entity_type,entity_id,file_name,mime_type,size_bytes,drive_file_id,drive_web_url,uploaded_by_id,uploaded_by_name,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,NOW())',[row.id,row.entityType,row.entityId,row.fileName,row.mimeType,row.sizeBytes,row.driveFileId,row.driveWebUrl,user.id,user.name]);await this.audit(user,'UPLOAD','EVIDENCE',row.id,{entityType:row.entityType,entityId:row.entityId});return row;}
  async listEvidence(entityType?:string,entityId?:string){if(this.demo())return this.evidence.filter(e=>(!entityType||e.entityType===entityType)&&(!entityId||e.entityId===entityId));let sql='SELECT id,entity_type,entity_id,file_name,mime_type,size_bytes,drive_file_id,drive_web_url,uploaded_by_name AS uploaded_by,created_at FROM evidence_files WHERE 1=1',params:any[]=[];if(entityType){sql+=' AND entity_type=?';params.push(entityType);}if(entityId){sql+=' AND entity_id=?';params.push(entityId);}return this.db.query<any>(sql+' ORDER BY created_at DESC',params);}
  async listAudit(){if(this.demo())return this.audits;return this.db.query<any>('SELECT id,actor_name,action,entity_type,entity_id,detail_json AS detail,created_at FROM audit_logs ORDER BY created_at DESC LIMIT 5000');}
  async reportSummary(){const [requests,registers,risks,incidents,evidence,dash]=await Promise.all([this.listRequests(),this.listRegisters(),this.listRisks(),this.listIncidents(),this.listEvidence(),this.dashboard()]);return{requests:requests.length,registers:registers.length,openRisks:risks.filter(r=>r.status!=='CLOSED').length,incidents:incidents.length,evidenceFiles:evidence.length,complianceRate:dash.metrics.complianceRate,generatedAt:now()};}
  async reportData(type:string){if(type==='requests')return this.listRequests();if(type==='registers')return this.listRegisters();if(type==='risks')return this.listRisks();if(type==='incidents')return this.listIncidents();if(type==='audit')return this.listAudit();throw new NotFoundException('ไม่พบประเภทรายงาน');}
}
