import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Plus, X } from 'lucide-react';
import { api } from '../lib/api';
import type { RegisterItem } from '../types';
import { EmptyState, ErrorNotice, LoadingBlock, PageHeader, SearchBox, StatusBadge } from '../components/UI';

const categories = [{ value: 'AI_TOOL', label: 'เครื่องมือ AI' },{ value: 'SYSTEM', label: 'ระบบ/Web Application' },{ value: 'DATASET', label: 'ชุดข้อมูล' },{ value: 'VENDOR', label: 'ผู้ให้บริการ' },{ value: 'INTEGRATION', label: 'API/การเชื่อมต่อ' },{ value: 'ADMIN_ACCOUNT', label: 'บัญชีผู้ดูแล' }];

export function RegistersPage() {
  const [items, setItems] = useState<RegisterItem[]>([]); const [category, setCategory] = useState('AI_TOOL'); const [query, setQuery] = useState(''); const [modal, setModal] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [form, setForm] = useState({ name: '', ownerName: '', department: '', classification: 'INTERNAL', reviewDate: '' });
  const load = () => api<{ items: RegisterItem[] }>(`/registers?category=${category}`).then((r) => setItems(r.items)).catch((e) => setError(e.message)).finally(() => setLoading(false));
  useEffect(() => { void load(); }, [category]);
  const filtered = useMemo(() => items.filter((i) => [i.code,i.name,i.ownerName,i.department].join(' ').toLowerCase().includes(query.toLowerCase())), [items, query]);
  async function submit(e: FormEvent) { e.preventDefault(); try { await api('/registers', { method: 'POST', body: JSON.stringify({ ...form, category }) }); setModal(false); setForm({ name:'',ownerName:'',department:'',classification:'INTERNAL',reviewDate:'' }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'บันทึกไม่สำเร็จ'); } }
  async function toggle(item:RegisterItem){try{await api(`/registers/${item.id}`,{method:'PATCH',body:JSON.stringify({status:item.status==='ACTIVE'?'SUSPENDED':'ACTIVE'})});await load();}catch(err){setError(err instanceof Error?err.message:'ปรับสถานะไม่สำเร็จ');}}
  return <div className="page"><PageHeader title="ทะเบียนกลาง" description="รายการที่โรงเรียนอนุมัติและกำหนดผู้รับผิดชอบแล้ว" action={<button className="button primary" onClick={() => setModal(true)}><Plus size={18}/>เพิ่มรายการ</button>}/>
    <div className="tabs">{categories.map((c) => <button key={c.value} className={category === c.value ? 'active' : ''} onClick={() => {setCategory(c.value); setLoading(true);}}>{c.label}</button>)}</div>
    <section className="panel"><div className="toolbar"><SearchBox value={query} onChange={setQuery} placeholder="ค้นหารหัส ชื่อรายการ หรือผู้รับผิดชอบ"/><span className="record-count">{filtered.length} รายการ</span></div>{error ? <ErrorNotice message={error}/> : loading ? <LoadingBlock/> : !filtered.length ? <EmptyState title="ยังไม่มีรายการในทะเบียน" description="เพิ่มรายการที่ได้รับอนุมัติและกำหนดวันทบทวน"/> : <div className="table-scroll"><table><thead><tr><th>รหัส</th><th>รายการ</th><th>เจ้าของ/หน่วยงาน</th><th>ระดับข้อมูล</th><th>วันทบทวน</th><th>สถานะ</th></tr></thead><tbody>{filtered.map((i) => <tr key={i.id}><td><strong>{i.code}</strong></td><td>{i.name}</td><td>{i.ownerName}<small>{i.department}</small></td><td>{i.classification}</td><td>{i.reviewDate ? new Date(i.reviewDate).toLocaleDateString('th-TH') : '-'}</td><td><StatusBadge value={i.status}/><button className="text-button" onClick={()=>toggle(i)}>{i.status==='ACTIVE'?'ระงับ':'เปิดใช้'}</button></td></tr>)}</tbody></table></div>}</section>
    {modal && <div className="modal-layer" role="dialog" aria-modal="true"><form className="modal-card" onSubmit={submit}><div className="modal-heading"><h2>เพิ่มรายการในทะเบียน</h2><button type="button" onClick={() => setModal(false)}><X/></button></div><label><span>ชื่อรายการ *</span><input required value={form.name} onChange={(e) => setForm({...form,name:e.target.value})}/></label><div className="form-grid"><label><span>เจ้าของรายการ *</span><input required value={form.ownerName} onChange={(e) => setForm({...form,ownerName:e.target.value})}/></label><label><span>หน่วยงาน *</span><input required value={form.department} onChange={(e) => setForm({...form,department:e.target.value})}/></label><label><span>ระดับข้อมูล</span><select value={form.classification} onChange={(e) => setForm({...form,classification:e.target.value})}><option value="PUBLIC">สาธารณะ</option><option value="INTERNAL">ใช้ภายใน</option><option value="CONFIDENTIAL">ส่วนบุคคล/ลับ</option><option value="RESTRICTED">อ่อนไหว/จำกัดสูง</option></select></label><label><span>วันทบทวน</span><input type="date" value={form.reviewDate} onChange={(e) => setForm({...form,reviewDate:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="button ghost" onClick={() => setModal(false)}>ยกเลิก</button><button className="button primary">บันทึกทะเบียน</button></div></form></div>}
  </div>;
}
