import { FormEvent, useEffect, useState } from 'react';
import { Plus, X } from 'lucide-react';
import { api } from '../lib/api';
import type { Risk } from '../types';
import { EmptyState, ErrorNotice, LoadingBlock, PageHeader, StatusBadge } from '../components/UI';

function level(score: number) { return score >= 17 ? 'CRITICAL' : score >= 10 ? 'HIGH' : score >= 5 ? 'MEDIUM' : 'LOW'; }
export function RisksPage() {
  const [items,setItems]=useState<Risk[]>([]); const [modal,setModal]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState('');
  const [form,setForm]=useState({title:'',category:'CYBER',likelihood:1,impact:1,controls:'',ownerName:'',dueDate:''});
  const load=()=>api<{items:Risk[]}>('/risks').then(r=>setItems(r.items)).catch(e=>setError(e.message)).finally(()=>setLoading(false)); useEffect(()=>{void load();},[]);
  async function submit(e:FormEvent){e.preventDefault();try{await api('/risks',{method:'POST',body:JSON.stringify(form)});setModal(false);await load();}catch(err){setError(err instanceof Error?err.message:'บันทึกไม่สำเร็จ');}}
  async function close(id:string){try{await api(`/risks/${id}`,{method:'PATCH',body:JSON.stringify({status:'CLOSED'})});await load();}catch(err){setError(err instanceof Error?err.message:'ปรับสถานะไม่สำเร็จ');}}
  const score=form.likelihood*form.impact;
  return <div className="page"><PageHeader title="ทะเบียนความเสี่ยง" description="ประเมินโอกาสเกิด ผลกระทบ มาตรการควบคุม และความเสี่ยงคงเหลือ" action={<button className="button primary" onClick={()=>setModal(true)}><Plus size={18}/>เพิ่มความเสี่ยง</button>}/>
    <section className="risk-summary"><div><span>ต่ำ</span><strong>{items.filter(i=>i.level==='LOW').length}</strong></div><div><span>ปานกลาง</span><strong>{items.filter(i=>i.level==='MEDIUM').length}</strong></div><div><span>สูง</span><strong>{items.filter(i=>i.level==='HIGH').length}</strong></div><div><span>วิกฤต</span><strong>{items.filter(i=>i.level==='CRITICAL').length}</strong></div></section>
    <section className="panel">{error?<ErrorNotice message={error}/>:loading?<LoadingBlock/>:!items.length?<EmptyState title="ยังไม่มีความเสี่ยง" description="เพิ่มความเสี่ยงและกำหนดมาตรการควบคุม"/>:<div className="table-scroll"><table><thead><tr><th>รหัส/ความเสี่ยง</th><th>ประเภท</th><th>โอกาส × ผลกระทบ</th><th>ระดับ</th><th>มาตรการควบคุม</th><th>เจ้าของ/กำหนด</th><th>สถานะ</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.code}</strong><small>{i.title}</small></td><td>{i.category}</td><td>{i.likelihood} × {i.impact} = <strong>{i.score}</strong></td><td><StatusBadge value={i.level}/></td><td className="wide-cell">{i.controls}</td><td>{i.ownerName}<small>{i.dueDate?new Date(i.dueDate).toLocaleDateString('th-TH'):'-'}</small></td><td><StatusBadge value={i.status}/>{i.status!=='CLOSED'&&<button className="text-button" onClick={()=>close(i.id)}>ปิดรายการ</button>}</td></tr>)}</tbody></table></div>}</section>
    {modal&&<div className="modal-layer"><form className="modal-card" onSubmit={submit}><div className="modal-heading"><h2>เพิ่มความเสี่ยง</h2><button type="button" onClick={()=>setModal(false)}><X/></button></div><label><span>ความเสี่ยง *</span><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="form-grid"><label><span>ประเภท</span><select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}><option value="AI">AI</option><option value="DATA">ข้อมูล</option><option value="CYBER">ไซเบอร์</option><option value="SYSTEM">ระบบดิจิทัล</option><option value="VENDOR">ผู้ให้บริการ</option></select></label><label><span>เจ้าของความเสี่ยง *</span><input required value={form.ownerName} onChange={e=>setForm({...form,ownerName:e.target.value})}/></label><label><span>โอกาสเกิด: {form.likelihood}</span><input type="range" min="1" max="5" value={form.likelihood} onChange={e=>setForm({...form,likelihood:Number(e.target.value)})}/></label><label><span>ผลกระทบ: {form.impact}</span><input type="range" min="1" max="5" value={form.impact} onChange={e=>setForm({...form,impact:Number(e.target.value)})}/></label><label className="full risk-result"><span>คะแนนประเมิน</span><strong>{score}</strong><StatusBadge value={level(score)}/></label><label className="full"><span>มาตรการควบคุม *</span><textarea required rows={3} value={form.controls} onChange={e=>setForm({...form,controls:e.target.value})}/></label><label><span>กำหนดแล้วเสร็จ</span><input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label></div><div className="form-actions"><button type="button" className="button ghost" onClick={()=>setModal(false)}>ยกเลิก</button><button className="button primary">บันทึกความเสี่ยง</button></div></form></div>}
  </div>;
}
